// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0e6FW6jwV9rvaz-nTPMuWgB9bG8QdQH0',
    appId: '1:666528643307:web:c458188a438d3317f3e6ae',
    messagingSenderId: '666528643307',
    projectId: 'etgroundchecklist',
    authDomain: 'etgroundchecklist.firebaseapp.com',
    storageBucket: 'etgroundchecklist.appspot.com',
    measurementId: 'G-Y024TMZYNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPRpeoK1S0Txv_2lYZF_9ijyMHQXXqqXA',
    appId: '1:666528643307:android:3fb611ed0b8cecb4f3e6ae',
    messagingSenderId: '666528643307',
    projectId: 'etgroundchecklist',
    storageBucket: 'etgroundchecklist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwIM36E10da8flRcRX07O8jdH0lVltzU',
    appId: '1:666528643307:ios:2185779060a13d72f3e6ae',
    messagingSenderId: '666528643307',
    projectId: 'etgroundchecklist',
    storageBucket: 'etgroundchecklist.appspot.com',
    iosBundleId: 'com.example.safetyCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLwIM36E10da8flRcRX07O8jdH0lVltzU',
    appId: '1:666528643307:ios:2185779060a13d72f3e6ae',
    messagingSenderId: '666528643307',
    projectId: 'etgroundchecklist',
    storageBucket: 'etgroundchecklist.appspot.com',
    iosBundleId: 'com.example.safetyCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0e6FW6jwV9rvaz-nTPMuWgB9bG8QdQH0',
    appId: '1:666528643307:web:c18f954d2c88b09ff3e6ae',
    messagingSenderId: '666528643307',
    projectId: 'etgroundchecklist',
    authDomain: 'etgroundchecklist.firebaseapp.com',
    storageBucket: 'etgroundchecklist.appspot.com',
    measurementId: 'G-EB4V5FEBVQ',
  );
}
